apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy29
  labels:
    app: autodeploy29
  namespace: namespace-workflow-1706564032774
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy29
  template:
    metadata:
      labels:
        app: autodeploy29
    spec:
      containers:
        - name: autodeploy29
          image: acrworkflow1706564032774.azurecr.io/image-workflow-1706564032774:latest
          ports:
            - containerPort: 5000